[repository]
name = "hyprcde"
authors = ["saucesaft"]

[hyprcde]
description = "CDE-like window decorations for hyprland."
authors = ["saucesaft, (forked from) Vaxry"]
output = "hyprcde.so"
build = [
    "make all"
]
